
# Extensions
require:
  - rubocop-rails

# Enable or disable new cops when gem updates
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

# Cop files-to-ignore
AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/**/*'
    - 'test/**/*'
    - 'db/migrate/*'
    - 'config.ru'
    - 'app/serializers/*'
    - 'app/channels/**/*'
    - 'app/jobs/*'
    - 'app/mailers/*'

Layout/LineLength:
  Max: 99

